query Foods {
  foods {
    id
    name
    brand
    calories
    servingSize
    servingUnit
    totalProteinInGrams
    totalCarbsInGrams
    totalFatInGrams
    polyunsaturatedFatInGrams
    monounsaturatedFatInGrams
    saturatedFatInGrams
    potassiumInMilligrams
    sodiumInMilligrams
    dietaryFiberInGrams
    sugarsInGrams
    cholesterolInMilligrams
    calciumInMilligrams
    ironInMilligrams
  }
}
