query BodyMeasurementByDate($date: Date!) {
  measurementsByDate(date: $date) {
    id
    createdAt
    goalId
    userId
    month
    year
    day
    bodyMeasurement {
      id
      createdAt
      logId
      weightInPounds
      heightInInches
      waterInMilliliters
      shouldersInInches
      forearmsInInches
      calvesInInches
      thighsInInches
      waistInInches
      chestInInches
      armsInInches
      neckInInches
      hipsInInches
      sleepInHours
      steps
    }
  }
}
