query BodyMeasurementByDate($date: LocalDate!) {
  bodyMeasurementByDate(date: $date) {
    id
    createdAt
    logId
    weightInPounds
    heightInInches
    waterInMilliliters
    shouldersInInches
    forearmsInInches
    calvesInInches
    thighsInInches
    waistInInches
    chestInInches
    armsInInches
    neckInInches
    hipsInInches
    sleepInHours
    steps
  }
}
