mutation UpsertBodyMeasurement(
  $date: Date!
  $data: UpsertBodyMeasurementInput!
) {
  upsertBodyMeasurement(date: $date, data: $data) {
    id
    createdAt
    logId
    weightInPounds
    heightInInches
    waterInMilliliters
    shouldersInInches
    forearmsInInches
    calvesInInches
    thighsInInches
    waistInInches
    chestInInches
    armsInInches
    neckInInches
    hipsInInches
    sleepInHours
    steps
  }
}
