mutation CreateGoal($data: CreateGoalInput!) {
  createGoal(data: $data) {
    id
    createdAt
    latest
    version
    waterInMilliliters
    weightInPounds
    sleepInHours
    proteinPercentage
    carbsPercentage
    fatPercentage
    calories
    steps
  }
}
