query GoalByClosestDate($date: LocalDate!) {
  goalByClosestDate(date: $date) {
    id
    createdAt
    waterInMilliliters
    weightInPounds
    sleepInHours
    proteinPercentage
    carbsPercentage
    fatPercentage
    calories
    steps
    date
  }
}
