query GoalByDate($date: Date!) {
  goalByDate(date: $date) {
    id
    createdAt
    latest
    version
    waterInMilliliters
    weightInPounds
    sleepInHours
    proteinPercentage
    carbsPercentage
    fatPercentage
    calories
    steps
  }
}
