query GoalByDate($date: Date!) {
  goalByDate(date: $date) {
    waterInMilliliters
    weightInPounds
    sleepInHours
    proteinPercentage
    carbsPercentage
    fatPercentage
    calories
    steps
  }
}
