query GoalByID($id: Uuid!) {
  goalByID(id: $id) {
    id
    createdAt
    latest
    version
    waterInMilliliters
    weightInPounds
    sleepInHours
    proteinPercentage
    carbsPercentage
    fatPercentage
    calories
    steps
  }
}
