query GoalByLatest {
  goalByLatest {
    id
    createdAt
    latest
    version
    waterInMilliliters
    weightInPounds
    sleepInHours
    proteinPercentage
    carbsPercentage
    fatPercentage
    calories
    steps
  }
}
