query FoodAnalytics(
  $key: FoodMeasurementKey!
  $date: InclusiveDateRangeInput!
  $options: TransformationOptionsInput
) {
  foodMeasurementsOverTime(key: $key, date: $date, options: $options) {
    key
    value
  }
  foodStats(date: $date) {
    key
    value
  }
}
