query FoodAnalytics(
  $key: FoodMeasurementKey!
  $date: InclusiveDateRangeInput!
  $options: TransformationOptionsInput
) {
  foodMeasurementsOverTime(key: $key, date: $date, options: $options) {
    id
    data {
      key
      value
    }
  }
  foodStats(date: $date) {
    id
    data {
      key
      value
    }
  }
}
