mutation CreateFoodMeasurementFromFoodID(
  $date: Date!
  $data: CreateFoodMeasurementFromFoodIdInput!
) {
  createFoodMeasurementFromFoodID(date: $date, data: $data) {
    id
    createdAt
    logId
    foodId
    servingsConsumed
  }
}
