mutation CreateFoodMeasurementFromFoodDetails(
  $date: Date!
  $data: CreateFoodMeasurementFromFoodDetailsInput!
) {
  createFoodMeasurementFromFoodDetails(date: $date, data: $data) {
    id
    createdAt
    logId
    foodId
    servingsConsumed
  }
}
