mutation CreateFoodMeasurementFromFoodDetails(
  $date: LocalDate!
  $data: CreateFoodMeasurementFromFoodDetailsInput!
) {
  createFoodMeasurementFromFoodDetails(date: $date, data: $data) {
    id
  }
}
