query FoodMeasurementsByDate($date: Date!) {
  measurementsByDate(date: $date) {
    id
    createdAt
    goalId
    userId
    month
    year
    day
    foodMeasurements {
      id
      createdAt
      logId
      foodId
      servingsConsumed
      food {
        id
        name
        brand
        calories
        servingSize
        servingUnit
        totalProteinInGrams
        totalCarbsInGrams
        totalFatInGrams
        polyunsaturatedFatInGrams
        monounsaturatedFatInGrams
        saturatedFatInGrams
        potassiumInMilligrams
        sodiumInMilligrams
        dietaryFiberInGrams
        sugarsInGrams
        cholesterolInMilligrams
        calciumInMilligrams
        ironInMilligrams
      }
    }
  }
}
